In [2]:
import numpy as np

"""
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.
"""

## function Vander_Monde_matrix 
def Vander_Monde_matrix(IP_vector, N, increase=False):
    if increase:
        OP_matrix = np.array([(x**(N-1-i)) for x in IP_vector for i in range(N)]).reshape(IP_vector.size, N)
    else:
        OP_matrix = np.array([x**i for x in IP_vector for i in range(N)]).reshape(IP_vector.size, N)
    return OP_matrix

In [3]:
print("-------------OUTPUT WITH N=3 ----------------------")
IP_vector = np.array([1,2,3,4,5])
N = 3
print("The Vander Matrix in Decreasing Order: \n\n",Vander_Monde_matrix(IP_vector, N, False))
print()
print("The Vander Matrix in Increasing Order: \n\n",Vander_Monde_matrix(IP_vector, N, True))


print("-------------OUTPUT WITH N=5----------------------")
IP_vector = np.array([1,2,3,4,5,6,7,8,9,10])
N = 5
print("The Vander Matrix in Decreasing Order: \n\n",Vander_Monde_matrix(IP_vector, N, False))
print()
print("The Vander Matrix in Increasing Order: \n\n",Vander_Monde_matrix(IP_vector, N, True))



-------------OUTPUT WITH N=3 ----------------------
The Vander Matrix in Decreasing Order: 

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]

The Vander Matrix in Increasing Order: 

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
-------------OUTPUT WITH N=5----------------------
The Vander Matrix in Decreasing Order: 

 [[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     3     9    27    81]
 [    1     4    16    64   256]
 [    1     5    25   125   625]
 [    1     6    36   216  1296]
 [    1     7    49   343  2401]
 [    1     8    64   512  4096]
 [    1     9    81   729  6561]
 [    1    10   100  1000 10000]]

The Vander Matrix in Increasing Order: 

 [[    1     1     1     1     1]
 [   16     8     4     2     1]
 [   81    27     9     3     1]
 [  256    64    16     4     1]
 [  625   125    25     5     1]
 [ 1296   216    36     6     1]
 [ 2401   343    49     7     1]
 [ 4096   512    64     8     1]
 [ 6561   